## $\Large{Numpy\; 練習題}$

In [1]:
import numpy as np

---
# 1-Dimension Array

## Exercise 1
使用np.arrange 函數創建一個數值從10到49的一維陣列

In [2]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Exercise 2
請建立一個陣列，裡頭包含0~101中所有完全平方數(ex. 1, 4, 9...)

In [5]:
arr = np.arange(0, 102)
print(np.square(arr))

[    0     1     4     9    16    25    36    49    64    81   100   121
   144   169   196   225   256   289   324   361   400   441   484   529
   576   625   676   729   784   841   900   961  1024  1089  1156  1225
  1296  1369  1444  1521  1600  1681  1764  1849  1936  2025  2116  2209
  2304  2401  2500  2601  2704  2809  2916  3025  3136  3249  3364  3481
  3600  3721  3844  3969  4096  4225  4356  4489  4624  4761  4900  5041
  5184  5329  5476  5625  5776  5929  6084  6241  6400  6561  6724  6889
  7056  7225  7396  7569  7744  7921  8100  8281  8464  8649  8836  9025
  9216  9409  9604  9801 10000 10201]


## Exercise 3
反轉陣列x使得陣列內的元素從尾排到頭

In [6]:
x = np.array([2, 0, 3, 1, 4, 7])

In [7]:
print(x[::-1])

[7 4 1 3 0 2]


## Exercise 4
將x陣列內數值介於3到8(包含3和8)的元素取負號

In [27]:
x = np.array([6, 2, 8, 3, 0, 1])

In [28]:


print(-x[(x >= 3) & (x <= 8)])

[-6 -8 -3]


## Exercise 5
創建一個長度為10的隨機數字陣列，並且將最大值取代為0

In [32]:
x = np.random.random((10))
print(x)
x[np.argmax(x)] = 0
print(x)

[0.1502944  0.85626414 0.72938429 0.52540108 0.5102622  0.5987104
 0.05182781 0.68637043 0.34932368 0.98711446]
[0.1502944  0.85626414 0.72938429 0.52540108 0.5102622  0.5987104
 0.05182781 0.68637043 0.34932368 0.        ]


## Exercise 6
從陣列x中取出符合以下條件的子集

(1) 不能被 3 整除

(2) 可以被 3 整除

(3) 可以被 3 或 5 整除

In [34]:
x = np.array([3, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])

In [36]:
y = x[x%3 != 0]
print(y)
z = x[x%3 == 0]
print(z)
a = x[(x%3 == 0) | (x%5 == 0)]
print(a)

[  4  10  89  43  46 100]
[ 3  6 24 45 99]
[  3   6  10  24  45  99 100]


## Exercise 7
使用np.arange建立從2019年1月到12月共12個月的陣列資料

範例結果如下
<img src='https://i.imgur.com/XrH8VCs.png'/>

In [39]:
使用np.arange建立從2019年1月到12月共12個月的陣列資料

NameError: name '使用np' is not defined

---
# n-Dimension Array

## Exercise 8
請以ndim與shape兩個用法印出陣列x的維度數目與各維度的長度

In [ ]:
x = np.array([[[[[[[[[[[[[[[[[5, 4, 3, 2, 1]]]], [[[[10, 9, 8, 7, 6]]]]]]]]]]]]]]]]])

## Exercise 9
使用np.random.random 函數創建一個3x3x3的陣列

## Exercise 10
創建一個5x5且數值介於0到4之間的整數陣列

## Exercise 11
創建一個擁有隨機數值且形狀為10x10的陣列，並且使用np.min 和 np.max兩函數找出陣列中的最大值/最小值

## Exercise 12
使用reshape函數將陣列x轉成最後一個維度的長度為1且第一個維度為3的3維陣列

In [ ]:
x = np.arange(9)

## Exercise 13
請針對x陣列中的每欄資料做累積加總

註：加總後的陣列數值將為 [[2, 6, 3], [7, 15, 4]]

In [ ]:
x = np.array([2, 6, 3, 5, 9, 1]).reshape(2, -1)

## Exercise 14
陣列標準化: 將x陣列內所有的元素除以x陣列內元素的最大值

In [ ]:
x = np.random.randn(6).reshape(2, 3)

## Exercise 15
請計算出x陣列中相鄰數字的差異並同樣存成np.array型態

註：由於x陣列有6個數字，因此相鄰數字的差異共會有5個數值，依序為 [-151, 224, -158, -88, 572]

In [ ]:
x = np.array([183, 32, 256, 98, 10, 582])

## Exercise 16
請將x陣列中所有數值可被3整除的元素索引列出

註：由於x為二維陣列，單一個元素的索引會有兩個數字(ex.[1, 0])

In [ ]:
x = np.arange(20).reshape(4, 5)

## Exercise 17
使用np.pad 函數在陣列x外圍加一層0，使得原本3x3的陣列變為5x5

In [ ]:
x = np.ones(shape=(3, 3))

## Exercise 18
計算x與y兩兩元素的乘積並做加總(答案應為32)

註：上述的做法其實就是矩陣內積，因此有超過兩種以上的作法可以計算出此答案，大家可以試試看自己會幾種

In [ ]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

## Exercise 19
使用np.concatenate函數將陣列x與陣列y合併在一起，使其與```np.append(x, y, axis = 1)```結果相同

In [ ]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

np.append(x, y, axis=1)

array([[1, 2, 3, 4, 5, 6]])

### 請參考 [100-numpy-exercises](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb) 做更多 numpy 的操作練習